spring:  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/healthcare
    username: ${dbusername}
    password: ${dbpassword}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 600000
  redis:
    host: localhost
    port: 6379
healthcare:
  module:
   vitalsign:
     uri: http://localhost:8083/vitalsign
     name: vitalsign-modul-api
   patient:
     uri: http://localhost:8082/patients
     name: patient-module-api
   user:
    uri: http://localhost:8081/users
    name: user-module-api  
management:
  endpoints:
    web:
      exposure:
        include: '*'
